// Music generated by ElevenLabs Music, for films that need more than the code synth. Every
// generation costs credits, so a track is cached by its request and never regenerated unless
// the request changes.
//
//   node core/audio/music.mjs <film-dir>/music.plan.json [--out dir]   (preferred)
//   node core/audio/music.mjs <film-dir>/music.prompt.txt --seconds 30 [--out dir]
//   → <dir>/music.wav (48 kHz stereo) + <dir>/music.meta.json; then measure it with beats.py.
//
// A plan (music_v2 composition_plan) enforces every section's duration, so hits land on the
// section boundaries the film needs. A free prompt treats the length as a suggestion only (a
// 34 s request came back 71 s long).
// music.plan.json: { "chunks": [ { "text": "[Intro] {instrumental}", "duration_ms": 3000,
//                                  "positive_styles": [...], "negative_styles": [...] }, ... ] }
//
// The key is read from the ELEVENLABS_API_KEY environment variable only (never printed or written).
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

function apiKey() {
  const key = process.env.ELEVENLABS_API_KEY;
  if (!key) throw new Error("set ELEVENLABS_API_KEY in the environment to generate music");
  return key.trim();
}

const duration = (file) =>
  Number(
    execFileSync("ffprobe", [
      "-v",
      "error",
      "-show_entries",
      "format=duration",
      "-of",
      "default=nw=1:nk=1",
      file,
    ]).toString(),
  );

export async function compose({ prompt, plan, seconds, out }) {
  const ms = plan
    ? plan.chunks.reduce((a, c) => a + c.duration_ms, 0)
    : Math.round(seconds * 1000);
  const request = plan
    ? { composition_plan: plan, model_id: "music_v2" }
    : { prompt, music_length_ms: ms, force_instrumental: true };
  const id = createHash("sha256")
    .update(JSON.stringify(request))
    .digest("hex")
    .slice(0, 16);
  const metaPath = join(out, "music.meta.json");
  const wav = join(out, "music.wav");
  const mp3 = join(out, "music.source.mp3");
  const cachedId = existsSync(metaPath)
    ? JSON.parse(readFileSync(metaPath, "utf8")).id
    : null;
  if (cachedId === id && existsSync(wav)) return { wav, cached: true };
  // The paid source mp3 is committed; the wav is rebuilt from it, so a fresh clone pays nothing.
  if (cachedId === id && existsSync(mp3)) {
    execFileSync("ffmpeg", [
      "-y",
      "-loglevel",
      "error",
      "-i",
      mp3,
      "-ar",
      "48000",
      "-ac",
      "2",
      wav,
    ]);
    return { wav, cached: true };
  }
  const res = await fetch(
    "https://api.elevenlabs.io/v1/music?output_format=mp3_48000_192",
    {
      method: "POST",
      headers: { "xi-api-key": apiKey(), "content-type": "application/json" },
      body: JSON.stringify(request),
    },
  );
  if (!res.ok)
    throw new Error(
      `ElevenLabs Music ${res.status}: ${(await res.text()).slice(0, 400)}`,
    );
  writeFileSync(mp3, Buffer.from(await res.arrayBuffer()));
  execFileSync("ffmpeg", [
    "-y",
    "-loglevel",
    "error",
    "-i",
    mp3,
    "-ar",
    "48000",
    "-ac",
    "2",
    wav,
  ]);
  const meta = {
    id,
    requested_s: ms / 1000,
    duration_s: duration(wav),
    mode: plan ? "music_v2 plan" : "prompt",
    generated: new Date().toISOString(),
  };
  writeFileSync(metaPath, `${JSON.stringify(meta, null, 1)}\n`);
  return { wav, cached: false, meta };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const input = process.argv[2];
  const get = (k) => {
    const i = process.argv.indexOf(`--${k}`);
    return i > 0 ? process.argv[i + 1] : undefined;
  };
  const isPlan = input?.endsWith(".json");
  if (!input || (!isPlan && !get("seconds"))) {
    console.error(
      "usage: node music.mjs <music.plan.json> | <prompt.txt> --seconds N  [--out dir]",
    );
    process.exit(2);
  }
  try {
    const text = readFileSync(input, "utf8");
    const r = await compose({
      plan: isPlan ? JSON.parse(text) : undefined,
      prompt: isPlan ? undefined : text.trim(),
      seconds: Number(get("seconds")),
      out: get("out") ?? dirname(input),
    });
    console.log(
      `${r.cached ? "cached" : "generated"} → ${r.wav}${r.meta ? ` (${r.meta.duration_s.toFixed(2)} s of ${r.meta.requested_s} s)` : ""}`,
    );
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
